name: CI

on:
  # Run this workflow on all push events
  push:

jobs:
  linter:
    name: Run Helm Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.2.1

      - name: Run linter
        run: helm lint --set dataKey=BLOB ./conjur-oss

  install-and-test:
    name: Create KinD cluster and install/test Conjur
    needs: [ linter ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kube-tag: [v1.18.2, v1.16.9, v1.14.10, v1.12.10]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.2.1

      - name: Create k8s KinD Cluster
        uses: helm/kind-action@v1.0.0-rc.1
        with:
          node_image: "kindest/node:${{ matrix.kube-tag }}"
          cluster_name: kube_${{ matrix.kube-tag }}

      - name: Run integration tests
        run: ./test-minimal.sh
